const fs = require('fs');
const path = require('path');

const indexFile = path.join(__dirname, 'index.html');
const appFile = path.join(__dirname, 'app.js');

let indexHtml = fs.readFileSync(indexFile, 'utf8');

// Inject data-i18n tags where missing
const replacements = [
    { find: '<span style="background: rgba(212,175,55,0.15); border: 1px solid rgba(212,175,55,0.4); color: #D4AF37; padding: 6px 16px; border-radius: 20px; font-size: 0.78rem; font-weight: 600; letter-spacing: 1px; text-transform: uppercase;">Acceso Rápido</span>', repl: '<span data-i18n="qs_badge" style="background: rgba(212,175,55,0.15); border: 1px solid rgba(212,175,55,0.4); color: #D4AF37; padding: 6px 16px; border-radius: 20px; font-size: 0.78rem; font-weight: 600; letter-spacing: 1px; text-transform: uppercase;">Acceso Rápido</span>' },
    
    // Panel Bathroom
    { find: '<h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Remodelacion de Banos</h3>', repl: '<h3 data-i18n="qs_bath_t1" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Remodelacion de Banos</h3>' },
    { find: '<p style="color: #718096; font-size: 0.88rem; margin: 0;">Diseno e instalacion completa de banos. Tina, ducha, lavabo, inodoro y plomeria nueva.</p>', repl: '<p data-i18n="qs_bath_d1" style="color: #718096; font-size: 0.88rem; margin: 0;">Diseno e instalacion completa de banos. Tina, ducha, lavabo, inodoro y plomeria nueva.</p>' },
    { find: '<a href="docs/eng_cobre.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>', repl: '<a data-i18n="qs_btn_view" href="docs/eng_cobre.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>' },

    { find: '<h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Drenajes y Desague</h3>', repl: '<h3 data-i18n="qs_bath_t2" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Drenajes y Desague</h3>' },
    { find: '<p style="color: #718096; font-size: 0.88rem; margin: 0;">Limpieza y reparacion de drenajes de bano, tina y lavabo con tecnologia de presion hidrostatica.</p>', repl: '<p data-i18n="qs_bath_d2" style="color: #718096; font-size: 0.88rem; margin: 0;">Limpieza y reparacion de drenajes de bano, tina y lavabo con tecnologia de presion hidrostatica.</p>' },

    { find: '<h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Valvulas y Griferia</h3>', repl: '<h3 data-i18n="qs_bath_t3" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Valvulas y Griferia</h3>' },
    { find: '<p style="color: #718096; font-size: 0.88rem; margin: 0;">Cambio de cartuchos, valvulas de ducha, llaves y mezcladores de marcas Moen, Delta, Kohler.</p>', repl: '<p data-i18n="qs_bath_d3" style="color: #718096; font-size: 0.88rem; margin: 0;">Cambio de cartuchos, valvulas de ducha, llaves y mezcladores de marcas Moen, Delta, Kohler.</p>' },
    { find: '<a href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;" onmouseover="this.style.background=\'rgba(212,175,55,0.1)\'" onmouseout="this.style.background=\'transparent\'">Agendar Revision</a>', repl: '<a data-i18n="qs_btn_schedule" href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;" onmouseover="this.style.background=\'rgba(212,175,55,0.1)\'" onmouseout="this.style.background=\'transparent\'">Agendar Revision</a>' },

    // Panel Heaters
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Tankless Water Heaters</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Instalacion y reemplazo de calentadores Navien, Rinnai y Bradford White. Ahorro de hasta 30% en energia.</p></div>', repl: '<div><h3 data-i18n="qs_heat_t1" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Tankless Water Heaters</h3><p data-i18n="qs_heat_d1" style="color: #718096; font-size: 0.88rem; margin: 0;">Instalacion y reemplazo de calentadores Navien, Rinnai y Bradford White. Ahorro de hasta 30% en energia.</p></div>' },
    { find: '<a href="docs/eng_valves.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>', repl: '<a data-i18n="qs_btn_view" href="docs/eng_valves.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Mantenimiento Preventivo</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Flush anual, revision de anodo y ajuste de temperatura para alargar la vida util del equipo.</p></div>', repl: '<div><h3 data-i18n="qs_heat_t2" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Mantenimiento Preventivo</h3><p data-i18n="qs_heat_d2" style="color: #718096; font-size: 0.88rem; margin: 0;">Flush anual, revision de anodo y ajuste de temperatura para alargar la vida util del equipo.</p></div>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Heat Pump Water Heaters</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Rebates disponibles en California. Calificamos bajo el programa de incentivos estatales TECH Clean CA.</p></div>', repl: '<div><h3 data-i18n="qs_heat_t3" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Heat Pump Water Heaters</h3><p data-i18n="qs_heat_d3" style="color: #718096; font-size: 0.88rem; margin: 0;">Rebates disponibles en California. Calificamos bajo el programa de incentivos estatales TECH Clean CA.</p></div>' },
    { find: '<a href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;" onmouseover="this.style.background=\'rgba(212,175,55,0.1)\'" onmouseout="this.style.background=\'transparent\'">Consultar Rebates</a>', repl: '<a data-i18n="qs_btn_rebates" href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;" onmouseover="this.style.background=\'rgba(212,175,55,0.1)\'" onmouseout="this.style.background=\'transparent\'">Consultar Rebates</a>' },

    // Panel Leaks
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Deteccion por Termografia</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Camaras termicas de alta resolucion para detectar fugas ocultas sin romper paredes. No invasivo.</p></div>', repl: '<div><h3 data-i18n="qs_leak_t1" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Deteccion por Termografia</h3><p data-i18n="qs_leak_d1" style="color: #718096; font-size: 0.88rem; margin: 0;">Camaras termicas de alta resolucion para detectar fugas ocultas sin romper paredes. No invasivo.</p></div>' },
    { find: '<a href="docs/eng_wh.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Tecnologia AI</a>', repl: '<a data-i18n="qs_btn_ai" href="docs/eng_wh.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Tecnologia AI</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Fugas en Slab</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Especialistas en deteccion y reparacion de fugas bajo la losa de concreto. Cobertura de seguro aplicable.</p></div>', repl: '<div><h3 data-i18n="qs_leak_t2" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Fugas en Slab</h3><p data-i18n="qs_leak_d2" style="color: #718096; font-size: 0.88rem; margin: 0;">Especialistas en deteccion y reparacion de fugas bajo la losa de concreto. Cobertura de seguro aplicable.</p></div>' },
    { find: '<a href="tel:+16692134422" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Diagnostico Urgente</a>', repl: '<a data-i18n="qs_btn_urg" href="tel:+16692134422" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Diagnostico Urgente</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">AI Leak Prediction</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Sistema predictivo con sensores IoT que alerta fugas antes de que ocurran. Instalacion disponible.</p></div>', repl: '<div><h3 data-i18n="qs_leak_t3" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">AI Leak Prediction</h3><p data-i18n="qs_leak_d3" style="color: #718096; font-size: 0.88rem; margin: 0;">Sistema predictivo con sensores IoT que alerta fugas antes de que ocurran. Instalacion disponible.</p></div>' },
    { find: '<a href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Mas Informacion</a>', repl: '<a data-i18n="qs_btn_more" href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Mas Informacion</a>' },

    // Panel Repipe
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Re-Pipe Completo</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Reemplazo total de tuberias galvanizadas o de cobre corroidas. Trabajo garantizado con permiso CSLB.</p></div>', repl: '<div><h3 data-i18n="qs_rep_t1" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Re-Pipe Completo</h3><p data-i18n="qs_rep_d1" style="color: #718096; font-size: 0.88rem; margin: 0;">Reemplazo total de tuberias galvanizadas o de cobre corroidas. Trabajo garantizado con permiso CSLB.</p></div>' },
    { find: '<a href="docs/eng_termografia.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>', repl: '<a data-i18n="qs_btn_view" href="docs/eng_termografia.html" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;" onmouseover="this.style.background=\'#c9a227\'" onmouseout="this.style.background=\'#D4AF37\'">Ver Detalles</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">PEX Piping</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Instalacion de tuberias PEX de ultima generacion. Flexible, resistente a la corrosion y de bajo costo.</p></div>', repl: '<div><h3 data-i18n="qs_rep_t2" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">PEX Piping</h3><p data-i18n="qs_rep_d2" style="color: #718096; font-size: 0.88rem; margin: 0;">Instalacion de tuberias PEX de ultima generacion. Flexible, resistente a la corrosion y de bajo costo.</p></div>' },
    { find: '<a href="tel:+16692134422" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Llamar Ahora</a>', repl: '<a data-i18n="qs_btn_call_now" href="tel:+16692134422" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Llamar Ahora</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Nueva Construccion</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Plomeria integral para proyectos residenciales y comerciales desde cero. Coordinamos permisos.</p></div>', repl: '<div><h3 data-i18n="qs_rep_t3" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Nueva Construccion</h3><p data-i18n="qs_rep_d3" style="color: #718096; font-size: 0.88rem; margin: 0;">Plomeria integral para proyectos residenciales y comerciales desde cero. Coordinamos permisos.</p></div>' },
    { find: '<a href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Consultar Proyecto</a>', repl: '<a data-i18n="qs_btn_proj" href="#contact" onclick="navigate(\'contact\'); return false;" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Consultar Proyecto</a>' },

    // Panel AI
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Joe AI - Diagnostico Gratis</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Describe tu problema a nuestro asistente Joe. Obtien diagnostico preliminar, materiales y presupuesto estimado al instante.</p></div>', repl: '<div><h3 data-i18n="qs_ai_t1" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Joe AI - Diagnostico Gratis</h3><p data-i18n="qs_ai_d1" style="color: #718096; font-size: 0.88rem; margin: 0;">Describe tu problema a nuestro asistente Joe. Obtien diagnostico preliminar, materiales y presupuesto estimado al instante.</p></div>' },
    { find: '<a href="docs/hazlo_tu_mismo.html?issue=custom" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Iniciar con Joe AI</a>', repl: '<a data-i18n="qs_btn_joe" href="docs/hazlo_tu_mismo.html?issue=custom" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Iniciar con Joe AI</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">EP Estimator Pro</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Presupuesto inteligente en segundos con materiales, mano de obra y margenes optimizados por IA.</p></div>', repl: '<div><h3 data-i18n="qs_ai_t2" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">EP Estimator Pro</h3><p data-i18n="qs_ai_d2" style="color: #718096; font-size: 0.88rem; margin: 0;">Presupuesto inteligente en segundos con materiales, mano de obra y margenes optimizados por IA.</p></div>' },
    { find: '<a href="https://ai.studio/apps/1a58c64e-2463-40ad-b1a5-9b7291ed3995" target="_blank" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Abrir Estimator</a>', repl: '<a data-i18n="qs_btn_est" href="https://ai.studio/apps/1a58c64e-2463-40ad-b1a5-9b7291ed3995" target="_blank" style="background: #D4AF37; color: #0A192F; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center;">Abrir Estimator</a>' },
    { find: '<div><h3 style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Termografia con IA</h3><p style="color: #718096; font-size: 0.88rem; margin: 0;">Analisis de imagenes termicas asistido por inteligencia artificial para detectar problemas invisibles al ojo humano.</p></div>', repl: '<div><h3 data-i18n="qs_ai_t3" style="color: #fff; font-size: 1.05rem; font-weight: 700; margin: 0 0 0.4rem;">Termografia con IA</h3><p data-i18n="qs_ai_d3" style="color: #718096; font-size: 0.88rem; margin: 0;">Analisis de imagenes termicas asistido por inteligencia artificial para detectar problemas invisibles al ojo humano.</p></div>' },
    { find: '<a href="docs/eng_termografia.html" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Ver Tecnologia</a>', repl: '<a data-i18n="qs_btn_tech" href="docs/eng_termografia.html" style="background: transparent; color: #D4AF37; padding: 10px; border-radius: 8px; font-weight: 700; font-size: 0.88rem; text-decoration: none; text-align: center; border: 1px solid #D4AF37;">Ver Tecnologia</a>' },

    // CTA
    { find: '<p style="color: #a0aec0; font-size: 0.9rem; margin: 0 0 1rem;">No encuentra su servicio? Llamenos y resolvemos cualquier necesidad de plomeria en San Jose, CA.</p>', repl: '<p data-i18n="qs_cta_desc" style="color: #a0aec0; font-size: 0.9rem; margin: 0 0 1rem;">No encuentra su servicio? Llamenos y resolvemos cualquier necesidad de plomeria en San Jose, CA.</p>' },
    { find: '<a href="mailto:moralesplumbing026@gmail.com" style="background: transparent; color: #D4AF37; padding: 12px 28px; border-radius: 8px; font-weight: 600; font-size: 0.95rem; text-decoration: none; border: 1px solid #D4AF37;">Email: moralesplumbing026@gmail.com</a>', repl: '<a data-i18n="qs_cta_email" href="mailto:moralesplumbing026@gmail.com" style="background: transparent; color: #D4AF37; padding: 12px 28px; border-radius: 8px; font-weight: 600; font-size: 0.95rem; text-decoration: none; border: 1px solid #D4AF37;">Email: moralesplumbing026@gmail.com</a>' }
];

replacements.forEach(r => {
    indexHtml = indexHtml.replace(r.find, r.repl);
});

fs.writeFileSync(indexFile, indexHtml);

// Now app.js
const translations = {
    "qs_badge": { en: "Quick Access", es: "Acceso Rápido", zh: "快速访问", tl: "Mabilis na Akses", vi: "Truy Cập Nhanh" },
    "qs_title": { en: "What service do you need?", es: "¿Qué servicio necesitas?", zh: "您需要什么服务？", tl: "Anong serbisyo ang kailangan mo?", vi: "Bạn cần dịch vụ gì?" },
    "qs_desc": { en: "Select your need and request an instant quote.", es: "Selecciona tu necesidad y solicita cotización al instante.", zh: "选择您的需求并请求即时报价。", tl: "Piliin ang iyong pangangailangan at humiling ng instant quote.", vi: "Chọn nhu cầu của bạn và yêu cầu báo giá tức thì." },
    "qs_tab_plumbing": { en: "General Plumbing", es: "Plomeria General", zh: "一般水管", tl: "Pangkalahatang Pagtutubero", vi: "Hệ thống ống nước" },
    "qs_tab_bathroom": { en: "Bath & Remodel", es: "Banos y Remodelacion", zh: "浴室和改造", tl: "Banyo at Pagbabago", vi: "Phòng tắm & Cải tạo" },
    "qs_tab_heaters": { en: "Water Heaters", es: "Water Heaters", zh: "热水器", tl: "Mga Water Heater", vi: "Máy nước nóng" },
    "qs_tab_leaks": { en: "Leak Detection", es: "Deteccion de Fugas", zh: "泄漏检测", tl: "Pagtuklas ng Tagas", vi: "Phát hiện rò rỉ" },
    "qs_tab_repipe": { en: "Re-Pipe", es: "Re-Pipe", zh: "重新布管", tl: "Re-Pipe", vi: "Re-Pipe" },
    "qs_tab_ai": { en: "AI Diagnosis", es: "AI Diagnosis", zh: "AI诊断", tl: "AI Diagnosis", vi: "AI Diagnosis" },

    "qs_plumb_t1": { en: "Pipe Repair", es: "Reparacion de Tuberias", zh: "管道维修", tl: "Pag-ayos ng Tubo", vi: "Sửa ống nước" },
    "qs_plumb_d1": { en: "Professional diagnosis and repair of broken, clogged or leaking pipes anywhere in the home.", es: "Diagnostico y reparacion profesional de tuberias rotas, obstruidas o filtradas en cualquier parte del hogar.", zh: "专业诊断和修复家中任何地方的破损、堵塞或漏水管道。", tl: "Propesyonal na pagsusuri at pagkumpuni ng mga sirang, barado o tumatagas na tubo kahit saan sa bahay.", vi: "Chẩn đoán và sửa chữa chuyên nghiệp các đường ống bị hỏng, tắc hoặc rò rỉ ở bất cứ đâu trong nhà." },
    "qs_btn_call": { en: "Call: (669) 213-4422", es: "Llamar: (669) 213-4422", zh: "致电: (669) 213-4422", tl: "Tumawag: (669) 213-4422", vi: "Gọi: (669) 213-4422" },
    "qs_plumb_t2": { en: "24/7 Emergencies", es: "Emergencias 24/7", zh: "24/7 紧急情况", tl: "24/7 Mga Emerhensiya", vi: "Cấp cứu 24/7" },
    "qs_plumb_d2": { en: "Flooding, burst pipes or total water loss. We respond in San Jose at no evaluation cost.", es: "Inundaciones, tuberias reventadas o perdida total de agua. Respondemos en San Jose sin costo de evaluacion.", zh: "洪水、管道爆裂或完全失水。我们在圣何塞响应，无评估费用。", tl: "Pagbaha, pumutok na tubo o kabuuang pagkawala ng tubig. Tumutugon kami sa San Jose nang walang gastos sa pagsusuri.", vi: "Ngập lụt, vỡ đường ống hoặc mất nước hoàn toàn. Chúng tôi phản hồi ở San Jose không tính phí đánh giá." },
    "qs_btn_emerg": { en: "Emergency Now", es: "Emergencia Ahora", zh: "立即紧急", tl: "Emerhensiya Ngayon", vi: "Cấp cứu Ngay" },
    "qs_plumb_t3": { en: "Plumbing Inspection", es: "Inspeccion de Plomeria", zh: "管道检查", tl: "Pagsusuri sa Pagtutubero", vi: "Kiểm tra hệ thống ống nước" },
    "qs_plumb_d3": { en: "Complete evaluation for home purchase/sale. Detailed report with thermography included.", es: "Evaluacion completa para compra/venta de vivienda. Reporte detallado con termografia incluida.", zh: "购房/售房的完整评估。包含热成像的详细报告。", tl: "Kumpletong pagsusuri para sa pagbili/pagbebenta ng bahay. Detalyadong ulat kasama ang thermography.", vi: "Đánh giá đầy đủ cho việc mua/bán nhà. Báo cáo chi tiết có bao gồm nhiệt kế." },
    "qs_btn_insp": { en: "Request Inspection", es: "Solicitar Inspeccion", zh: "请求检查", tl: "Humiling ng Pagsusuri", vi: "Yêu cầu Kiểm tra" },

    "qs_bath_t1": { en: "Bathroom Remodeling", es: "Remodelacion de Banos", zh: "浴室改造", tl: "Pag-aayos ng Banyo", vi: "Cải tạo Phòng tắm" },
    "qs_bath_d1": { en: "Design and full bathroom installation. Tub, shower, sink, toilet, and new plumbing.", es: "Diseno e instalacion completa de banos. Tina, ducha, lavabo, inodoro y plomeria nueva.", zh: "设计和完整的浴室安装。浴缸、淋浴、水槽、马桶和新管道。", tl: "Disenyo at buong pag-install ng banyo. Tub, shower, lababo, inidoro, at bagong pagtutubero.", vi: "Thiết kế và lắp đặt phòng tắm đầy đủ. Bồn tắm, vòi hoa sen, bồn rửa, nhà vệ sinh và hệ thống ống nước mới." },
    "qs_btn_view": { en: "View Details", es: "Ver Detalles", zh: "查看详情", tl: "Tingnan ang mga Detalye", vi: "Xem Chi tiết" },
    "qs_bath_t2": { en: "Drains & Sewers", es: "Drenajes y Desague", zh: "排水和下水道", tl: "Mga Drain at Imburnal", vi: "Ống thoát nước & cống" },
    "qs_bath_d2": { en: "Cleaning and repair of bath, tub and sink drains with hydrostatic pressure technology.", es: "Limpieza y reparacion de drenajes de bano, tina y lavabo con tecnologia de presion hidrostatica.", zh: "采用静压技术清洗和修复浴缸、水槽和下水道排水管。", tl: "Paglilinis at pagkumpuni ng mga drain ng banyo, tub at lababo na may hydrostatic pressure technology.", vi: "Làm sạch và sửa chữa các ống xả bồn tắm, bồn rửa và chậu rửa bằng công nghệ áp suất thủy tĩnh." },
    "qs_bath_t3": { en: "Valves & Faucets", es: "Valvulas y Griferia", zh: "阀门和水龙头", tl: "Mga Balbula at Gripo", vi: "Van & Vòi" },
    "qs_bath_d3": { en: "Replacement of cartridges, shower valves, faucets, and mixers from Moen, Delta, Kohler.", es: "Cambio de cartuchos, valvulas de ducha, llaves y mezcladores de marcas Moen, Delta, Kohler.", zh: "更换 Moen、Delta、Kohler 品牌的阀芯、淋浴阀、水龙头和混合器。", tl: "Pagpapalit ng mga cartridge, balbula ng shower, gripo, at mixer mula sa Moen, Delta, Kohler.", vi: "Thay thế hộp mực, van vòi hoa sen, vòi và máy trộn từ Moen, Delta, Kohler." },
    "qs_btn_schedule": { en: "Schedule Review", es: "Agendar Revision", zh: "安排检查", tl: "Mag-iskedyul ng Pagsusuri", vi: "Lên lịch Đánh giá" },

    "qs_heat_t1": { en: "Tankless Water Heaters", es: "Tankless Water Heaters", zh: "无罐热水器", tl: "Mga Tankless Water Heater", vi: "Máy nước nóng không bình chứa" },
    "qs_heat_d1": { en: "Installation and replacement of Navien, Rinnai, and Bradford White heaters. Save up to 30% in energy.", es: "Instalacion y reemplazo de calentadores Navien, Rinnai y Bradford White. Ahorro de hasta 30% en energia.", zh: "安装和更换 Navien、Rinnai 和 Bradford White 热水器。节省高达 30% 的能源。", tl: "Pag-install at pagpapalit ng mga heater ng Navien, Rinnai, at Bradford White. Makatipid ng hanggang 30% sa enerhiya.", vi: "Lắp đặt và thay thế máy nước nóng Navien, Rinnai và Bradford White. Tiết kiệm tới 30% năng lượng." },
    "qs_heat_t2": { en: "Preventive Maintenance", es: "Mantenimiento Preventivo", zh: "预防性维护", tl: "Preventive Maintenance", vi: "Bảo trì phòng ngừa" },
    "qs_heat_d2": { en: "Annual flush, anode check, and temp adjustment to extend unit life.", es: "Flush anual, revision de anodo y ajuste de temperatura para alargar la vida util del equipo.", zh: "年度冲洗、阳极检查和温度调节，以延长设备寿命。", tl: "Taunang flush, pagsusuri sa anode, at pagsasaayos ng temperatura upang pahabain ang buhay ng unit.", vi: "Xả hàng năm, kiểm tra cực dương và điều chỉnh nhiệt độ để kéo dài tuổi thọ thiết bị." },
    "qs_heat_t3": { en: "Heat Pump Water Heaters", es: "Heat Pump Water Heaters", zh: "热泵热水器", tl: "Mga Heat Pump Water Heater", vi: "Máy nước nóng bơm nhiệt" },
    "qs_heat_d3": { en: "Rebates available in California. We qualify under the TECH Clean CA state incentive program.", es: "Rebates disponibles en California. Calificamos bajo el programa de incentivos estatales TECH Clean CA.", zh: "加州提供返利。我们符合 TECH Clean CA 州奖励计划。", tl: "Available ang mga rebate sa California. Kwalipikado kami sa ilalim ng TECH Clean CA state incentive program.", vi: "Có sẵn các khoản giảm giá ở California. Chúng tôi đủ điều kiện theo chương trình khuyến khích của tiểu bang TECH Clean CA." },
    "qs_btn_rebates": { en: "Consult Rebates", es: "Consultar Rebates", zh: "咨询返利", tl: "Kumonsulta sa mga Rebate", vi: "Tư vấn Giảm giá" },

    "qs_leak_t1": { en: "Thermography Detection", es: "Deteccion por Termografia", zh: "热成像检测", tl: "Thermography Detection", vi: "Phát hiện bằng nhiệt kế" },
    "qs_leak_d1": { en: "High-resolution thermal cameras to detect hidden leaks without breaking walls. Non-invasive.", es: "Camaras termicas de alta resolucion para detectar fugas ocultas sin romper paredes. No invasivo.", zh: "高分辨率热像仪无需破墙即可检测隐蔽泄漏。非侵入式。", tl: "High-resolution thermal camera upang makita ang mga nakatagong tagas nang hindi sinisira ang mga pader. Hindi invasive.", vi: "Camera nhiệt độ phân giải cao để phát hiện rò rỉ ẩn mà không cần phá vỡ tường. Không xâm lấn." },
    "qs_btn_ai": { en: "View AI Tech", es: "Ver Tecnologia AI", zh: "查看AI技术", tl: "Tingnan ang AI Tech", vi: "Xem Công nghệ AI" },
    "qs_leak_t2": { en: "Slab Leaks", es: "Fugas en Slab", zh: "平板漏水", tl: "Mga Slab Leak", vi: "Rò rỉ Slab" },
    "qs_leak_d2": { en: "Specialists in detection and repair of leaks under the concrete slab. Insurance coverage applicable.", es: "Especialistas en deteccion y reparacion de fugas bajo la losa de concreto. Cobertura de seguro aplicable.", zh: "专业检测和修复混凝土地板下的漏水。适用保险理赔。", tl: "Mga espesyalista sa pagtuklas at pagkumpuni ng mga tagas sa ilalim ng kongkretong slab. Naaangkop ang saklaw ng seguro.", vi: "Chuyên gia phát hiện và sửa chữa rò rỉ dưới tấm bê tông. Bảo hiểm có thể áp dụng." },
    "qs_btn_urg": { en: "Urgent Diagnosis", es: "Diagnostico Urgente", zh: "紧急诊断", tl: "Kagyat na Pagsusuri", vi: "Chẩn đoán Khẩn cấp" },
    "qs_leak_t3": { en: "AI Leak Prediction", es: "AI Leak Prediction", zh: "AI漏水预测", tl: "AI Leak Prediction", vi: "Dự đoán rò rỉ AI" },
    "qs_leak_d3": { en: "Predictive system with IoT sensors that alert leaks before they happen. Installation available.", es: "Sistema predictivo con sensores IoT que alerta fugas antes de que ocurran. Instalacion disponible.", zh: "带IoT传感器的预测系统，在泄漏发生前发出警报。可提供安装。", tl: "Predictive system na may mga IoT sensor na nag-aalerto sa mga tagas bago pa ito mangyari. Available ang pag-install.", vi: "Hệ thống dự đoán với cảm biến IoT cảnh báo rò rỉ trước khi chúng xảy ra. Có sẵn cài đặt." },
    "qs_btn_more": { en: "More Info", es: "Mas Informacion", zh: "更多信息", tl: "Karagdagang Impormasyon", vi: "Thêm thông tin" },

    "qs_rep_t1": { en: "Complete Re-Pipe", es: "Re-Pipe Completo", zh: "完整重新布管", tl: "Kumpletong Re-Pipe", vi: "Thay thế toàn bộ đường ống" },
    "qs_rep_d1": { en: "Total replacement of corroded galvanized or copper pipes. Work guaranteed with CSLB permit.", es: "Reemplazo total de tuberias galvanizadas o de cobre corroidas. Trabajo garantizado con permiso CSLB.", zh: "完全更换腐蚀的镀锌管或铜管。提供 CSLB 许可证担保的工作。", tl: "Kabuuang pagpapalit ng mga corroded na galvanized o copper na tubo. Garantisadong trabaho na may CSLB permit.", vi: "Thay thế hoàn toàn các ống mạ kẽm hoặc đồng bị ăn mòn. Công việc được bảo đảm với giấy phép CSLB." },
    "qs_rep_t2": { en: "PEX Piping", es: "PEX Piping", zh: "PEX 管道", tl: "PEX Piping", vi: "Hệ thống ống PEX" },
    "qs_rep_d2": { en: "Installation of latest generation PEX pipes. Flexible, corrosion resistant and low cost.", es: "Instalacion de tuberias PEX de ultima generacion. Flexible, resistente a la corrosion y de bajo costo.", zh: "安装最新一代的 PEX 管道。灵活，耐腐蚀且成本低。", tl: "Pag-install ng pinakabagong henerasyon ng mga PEX pipe. Flexible, corrosion resistant at mababang gastos.", vi: "Lắp đặt ống PEX thế hệ mới nhất. Linh hoạt, chống ăn mòn và chi phí thấp." },
    "qs_btn_call_now": { en: "Call Now", es: "Llamar Ahora", zh: "立即致电", tl: "Tumawag Ngayon", vi: "Gọi Ngay" },
    "qs_rep_t3": { en: "New Construction", es: "Nueva Construccion", zh: "新建筑", tl: "Bagong Konstruksyon", vi: "Xây dựng Mới" },
    "qs_rep_d3": { en: "Integral plumbing for residential and commercial projects from scratch. We coordinate permits.", es: "Plomeria integral para proyectos residenciales y comerciales desde cero. Coordinamos permisos.", zh: "从头开始提供住宅和商业项目的完整管道服务。我们协调许可证。", tl: "Integral na pagtutubero para sa mga residential at commercial na proyekto mula sa simula. Kami ay nag-coordinate ng mga permit.", vi: "Hệ thống ống nước tích hợp cho các dự án dân cư và thương mại từ đầu. Chúng tôi điều phối giấy phép." },
    "qs_btn_proj": { en: "Consult Project", es: "Consultar Proyecto", zh: "咨询项目", tl: "Kumonsulta sa Proyekto", vi: "Tư vấn Dự án" },

    "qs_ai_t1": { en: "Joe AI - Free Diagnosis", es: "Joe AI - Diagnostico Gratis", zh: "Joe AI - 免费诊断", tl: "Joe AI - Libreng Pagsusuri", vi: "Joe AI - Chẩn đoán Miễn phí" },
    "qs_ai_d1": { en: "Describe your issue to our Joe assistant. Get preliminary diagnosis, materials and estimated budget instantly.", es: "Describe tu problema a nuestro asistente Joe. Obtien diagnostico preliminar, materiales y presupuesto estimado al instante.", zh: "向我们的 Joe 助手描述您的问题。立即获得初步诊断、材料和估计预算。", tl: "Ilarawan ang iyong isyu sa aming Joe assistant. Kumuha ng paunang pagsusuri, materyales at tinantyang badyet kaagad.", vi: "Mô tả vấn đề của bạn cho trợ lý Joe của chúng tôi. Nhận chẩn đoán sơ bộ, vật liệu và ngân sách ước tính ngay lập tức." },
    "qs_btn_joe": { en: "Start with Joe AI", es: "Iniciar con Joe AI", zh: "从 Joe AI 开始", tl: "Magsimula sa Joe AI", vi: "Bắt đầu với Joe AI" },
    "qs_ai_t2": { en: "EP Estimator Pro", es: "EP Estimator Pro", zh: "EP 估算器专业版", tl: "EP Estimator Pro", vi: "EP Estimator Pro" },
    "qs_ai_d2": { en: "Smart budget in seconds with materials, labor and AI optimized margins.", es: "Presupuesto inteligente en segundos con materiales, mano de obra y margenes optimizados por IA.", zh: "只需几秒钟的智能预算，包含材料、人工和 AI 优化利润率。", tl: "Smart budget sa ilang segundo kasama ang mga materyales, paggawa at mga AI optimized margin.", vi: "Ngân sách thông minh trong vài giây với vật liệu, lao động và biên lợi nhuận được tối ưu hóa bằng AI." },
    "qs_btn_est": { en: "Open Estimator", es: "Abrir Estimator", zh: "打开估算器", tl: "Buksan ang Estimator", vi: "Mở Estimator" },
    "qs_ai_t3": { en: "AI Thermography", es: "Termografia con IA", zh: "AI 热成像", tl: "AI Thermography", vi: "Nhiệt kế AI" },
    "qs_ai_d3": { en: "Analysis of thermal images assisted by AI to detect problems invisible to the human eye.", es: "Analisis de imagenes termicas asistido por inteligencia artificial para detectar problemas invisibles al ojo humano.", zh: "通过人工智能辅助分析热图像，检测人眼看不见的问题。", tl: "Pagsusuri ng mga thermal image na tinulungan ng AI upang makita ang mga problemang hindi nakikita ng mata ng tao.", vi: "Phân tích hình ảnh nhiệt được hỗ trợ bởi AI để phát hiện các vấn đề mà mắt người không nhìn thấy được." },
    "qs_btn_tech": { en: "View Tech", es: "Ver Tecnologia", zh: "查看技术", tl: "Tingnan ang Teknolohiya", vi: "Xem Công nghệ" },

    "qs_cta_desc": { en: "Can't find your service? Call us and we will solve any plumbing need in San Jose, CA.", es: "No encuentra su servicio? Llamenos y resolvemos cualquier necesidad de plomeria en San Jose, CA.", zh: "找不到您的服务？请致电我们，我们将解决加州圣何塞的任何管道需求。", tl: "Hindi mahanap ang iyong serbisyo? Tawagan kami at lulutasin namin ang anumang pangangailangan sa pagtutubero sa San Jose, CA.", vi: "Không thể tìm thấy dịch vụ của bạn? Hãy gọi cho chúng tôi và chúng tôi sẽ giải quyết mọi nhu cầu về hệ thống ống nước ở San Jose, CA." },
    "qs_cta_email": { en: "Email: moralesplumbing026@gmail.com", es: "Email: moralesplumbing026@gmail.com", zh: "电子邮件: moralesplumbing026@gmail.com", tl: "Email: moralesplumbing026@gmail.com", vi: "Email: moralesplumbing026@gmail.com" }
};

let appJsStr = fs.readFileSync(appFile, 'utf8');

// Inject the translations into the main translations object
for (let lang of ['en', 'es', 'zh', 'tl', 'vi']) {
    let langMatch = appJsStr.match(new RegExp(`"${lang}":\\s*{`));
    if (langMatch) {
        let insertIndex = langMatch.index + langMatch[0].length;
        
        let injectStr = '\n';
        for (let key in translations) {
            let val = translations[key][lang].replace(/"/g, '\\"');
            injectStr += `        "${key}": "${val}",\n`;
        }
        
        appJsStr = appJsStr.slice(0, insertIndex) + injectStr + appJsStr.slice(insertIndex);
    }
}

fs.writeFileSync(appFile, appJsStr);
console.log("Done");
