const fs = require('fs');
let code = fs.readFileSync('app.js', 'utf8');

const additions = {
    'en': ',\n        "services_title": "Expert Plumbing Solutions",\n        "services_desc": "High-tech diagnostic and precision repair for residential and commercial hydraulic systems.",\n        "srv_drain_title": "Drain & Sewer",\n        "srv_drain_1": "Camera Inspection & Cleaning",\n        "srv_drain_2": "High-Pressure HydroJetting",\n        "srv_drain_3": "Trenchless Sewer Repair",\n        "srv_heater_title": "Water Heaters",\n        "srv_heater_1": "High-Efficiency Tankless Systems",\n        "srv_heater_2": "Traditional Tank Replacement",\n        "srv_heater_3": "Maintenance & Descaling",\n        "srv_gen_title": "General Plumbing",\n        "srv_gen_1": "Leaks & Frozen Pipes",\n        "srv_gen_2": "Toilet & Faucet Repair",\n        "srv_gen_3": "Pressure Regulators (PRV)",\n        "srv_water_title": "Water Quality",\n        "srv_water_1": "Whole House Filtration",\n        "srv_water_2": "Water Softener Systems",\n        "srv_water_3": "Reverse Osmosis Systems",\n        "btn_book_srv": "Schedule Service",\n        "btn_learn_more": "Learn More"',
    'es': ',\n        "services_title": "Soluciones Expertas de Plomería",\n        "services_desc": "Diagnóstico de alta tecnología y reparación de precisión para sistemas hidráulicos residenciales y comerciales.",\n        "srv_drain_title": "Drenajes y Alcantarillado",\n        "srv_drain_1": "Limpieza e Inspección con Cámara",\n        "srv_drain_2": "HydroJetting de Alta Presión",\n        "srv_drain_3": "Reparación Sin Zanja (Trenchless)",\n        "srv_heater_title": "Calentadores de Agua",\n        "srv_heater_1": "Sistemas Tankless (Alta Eficiencia)",\n        "srv_heater_2": "Reemplazo de Tanques Tradicionales",\n        "srv_heater_3": "Mantenimiento y Descalcificación",\n        "srv_gen_title": "Plomería General",\n        "srv_gen_1": "Fugas y Tuberías Congeladas",\n        "srv_gen_2": "Reparación de Inodoros y Grifos",\n        "srv_gen_3": "Reguladores de Presión (PRV)",\n        "srv_water_title": "Calidad de Agua",\n        "srv_water_1": "Filtros de Casa Completa",\n        "srv_water_2": "Suavizadores de Agua",\n        "srv_water_3": "Sistemas de Ósmosis Inversa",\n        "btn_book_srv": "Agendar Servicio",\n        "btn_learn_more": "Saber Más"',
    'zh': ',\n        "services_title": "专家级管道解决方案",\n        "services_desc": "为住宅和商业水压系统提供高科技诊断和精准维修。",\n        "srv_drain_title": "排水与下水道",\n        "srv_drain_1": "摄像头检查与清洁",\n        "srv_drain_2": "高压水射流清洗",\n        "srv_drain_3": "无沟槽下水道维修",\n        "srv_heater_title": "热水器",\n        "srv_heater_1": "高效无罐系统",\n        "srv_heater_2": "传统储水罐更换",\n        "srv_heater_3": "维护与除垢",\n        "srv_gen_title": "常规管道",\n        "srv_gen_1": "漏水与管道结冰",\n        "srv_gen_2": "马桶与水龙头维修",\n        "srv_gen_3": "减压阀 (PRV)",\n        "srv_water_title": "水质处理",\n        "srv_water_1": "全屋过滤系统",\n        "srv_water_2": "软水器系统",\n        "srv_water_3": "反渗透系统",\n        "btn_book_srv": "预约服务",\n        "btn_learn_more": "了解更多"',
    'tl': ',\n        "services_title": "Dalubhasang Solusyon sa Pagtutubero",\n        "services_desc": "High-tech na diagnostic at tumpak na pag-aayos para sa residential at commercial hydraulic systems.",\n        "srv_drain_title": "Drain at Alkantarilya",\n        "srv_drain_1": "Camera Inspection at Paglilinis",\n        "srv_drain_2": "High-Pressure HydroJetting",\n        "srv_drain_3": "Trenchless Sewer Repair",\n        "srv_heater_title": "Water Heaters",\n        "srv_heater_1": "High-Efficiency Tankless Systems",\n        "srv_heater_2": "Traditional Tank Replacement",\n        "srv_heater_3": "Maintenance at Descaling",\n        "srv_gen_title": "Pangkalahatang Pagtutubero",\n        "srv_gen_1": "Leaks at Frozen Pipes",\n        "srv_gen_2": "Pag-aayos ng Toilet at Faucet",\n        "srv_gen_3": "Pressure Regulators (PRV)",\n        "srv_water_title": "Kalidad ng Tubig",\n        "srv_water_1": "Whole House Filtration",\n        "srv_water_2": "Water Softener Systems",\n        "srv_water_3": "Reverse Osmosis Systems",\n        "btn_book_srv": "Mag-iskedyul ng Serbisyo",\n        "btn_learn_more": "Alamin ang Iba Pa"',
    'vi': ',\n        "services_title": "Giải Pháp Ống Nước Chuyên Nghiệp",\n        "services_desc": "Chẩn đoán công nghệ cao và sửa chữa chính xác cho hệ thống thủy lực dân dụng và thương mại.",\n        "srv_drain_title": "Cống & Nước Thải",\n        "srv_drain_1": "Kiểm Tra Camera & Làm Sạch",\n        "srv_drain_2": "Phun Nước Áp Lực Cao (HydroJetting)",\n        "srv_drain_3": "Sửa Chữa Cống Không Đào Rãnh",\n        "srv_heater_title": "Máy Nước Nóng",\n        "srv_heater_1": "Hệ Thống Không Bình Chứa Hiệu Suất Cao",\n        "srv_heater_2": "Thay Thế Bình Chứa Truyền Thống",\n        "srv_heater_3": "Bảo Trì & Tẩy Cặn",\n        "srv_gen_title": "Ống Nước Tổng Hợp",\n        "srv_gen_1": "Rò Rỉ & Ống Nước Đóng Băng",\n        "srv_gen_2": "Sửa Bồn Cầu & Vòi Nước",\n        "srv_gen_3": "Bộ Điều Chỉnh Áp Suất (PRV)",\n        "srv_water_title": "Chất Lượng Nước",\n        "srv_water_1": "Hệ Thống Lọc Toàn Nhà",\n        "srv_water_2": "Hệ Thống Làm Mềm Nước",\n        "srv_water_3": "Hệ Thống Thẩm Thấu Ngược (RO)",\n        "btn_book_srv": "Lên Lịch Dịch Vụ",\n        "btn_learn_more": "Tìm Hiểu Thêm"'
};

const langs = ['en', 'es', 'zh', 'tl', 'vi'];

for (let i = 0; i < langs.length; i++) {
    const lang = langs[i];
    let startIndex = code.indexOf('"' + lang + '": {');
    if (startIndex === -1) continue;
    let endIndex = i < langs.length - 1 ? code.indexOf('"' + langs[i+1] + '": {', startIndex) : code.indexOf('};', startIndex);
    
    let block = code.substring(startIndex, endIndex);
    let lastBraceIdx = block.lastIndexOf('    }');
    if (lastBraceIdx !== -1) {
        block = block.substring(0, lastBraceIdx) + additions[lang] + '\n' + block.substring(lastBraceIdx);
        code = code.substring(0, startIndex) + block + code.substring(endIndex);
    }
}

fs.writeFileSync('app.js', code);
console.log('Service translations injected successfully!');
