import re

with open('app.js', 'r', encoding='utf-8') as f:
    appjs_content = f.read()

trans = {
    'en': {
        "htm_title": "Hazlo Tú Mismo (DIY)",
        "htm_subtitle": "Top 10 Easy Home Repairs from FAQ 100",
        "htm_joe_title": "Joe AI Assistant",
        "htm_joe_desc": "Select a task to get material calculations, or ask me to navigate.",
        "htm_calc_btn": "Calculate Materials",
        "htm_materials": "Materials Needed",
        "htm_tools": "Tools Required",
        "htm_steps": "Step-by-Step",
        "htm_disposal_title": "1. Unjam Garbage Disposal",
        "htm_disposal_desc": "Free up a jammed motor easily.",
        "htm_heater_title": "2. Reset Water Heater",
        "htm_heater_desc": "Restore hot water after a thermal trip.",
        "htm_toilet_title": "3. Fix Running Toilet",
        "htm_toilet_desc": "Stop the constant flow of water.",
        "htm_sink_title": "4. Clear Sink P-Trap",
        "htm_sink_desc": "Unclog your sink mechanically.",
        "htm_aerator_title": "5. Clean Faucet Aerator",
        "htm_aerator_desc": "Fix low water pressure at the sink.",
        "htm_faucet_title": "6. Fix Leaky Faucet",
        "htm_faucet_desc": "Stop a dripping faucet.",
        "htm_caulk_title": "7. Re-Caulk Bathtub",
        "htm_caulk_desc": "Prevent water damage and mold.",
        "htm_showerhead_title": "8. Replace Showerhead",
        "htm_showerhead_desc": "Upgrade your shower experience.",
        "htm_smell_title": "9. Eliminate Sewer Odor",
        "htm_smell_desc": "Block gases by priming dry traps.",
        "htm_washer_hose_title": "10. Replace Washer Hoses",
        "htm_washer_hose_desc": "Prevent laundry room floods."
    },
    'es': {
        "htm_title": "Hazlo Tú Mismo (DIY)",
        "htm_subtitle": "Top 10 Reparaciones Fáciles del FAQ 100",
        "htm_joe_title": "Asistente Joe AI",
        "htm_joe_desc": "Selecciona una tarea para calcular materiales o pídeme que navegue.",
        "htm_calc_btn": "Calcular Materiales",
        "htm_materials": "Materiales Necesarios",
        "htm_tools": "Herramientas Requeridas",
        "htm_steps": "Paso a Paso",
        "htm_disposal_title": "1. Destrabar Triturador",
        "htm_disposal_desc": "Libera un motor atascado fácilmente.",
        "htm_heater_title": "2. Reiniciar Calentador",
        "htm_heater_desc": "Restaura el agua caliente tras un corte térmico.",
        "htm_toilet_title": "3. Arreglar Inodoro",
        "htm_toilet_desc": "Detén el flujo constante de agua.",
        "htm_sink_title": "4. Limpiar Trampa P",
        "htm_sink_desc": "Destapa tu lavamanos mecánicamente.",
        "htm_aerator_title": "5. Limpiar Aereador",
        "htm_aerator_desc": "Arregla la baja presión en el lavamanos.",
        "htm_faucet_title": "6. Reparar Llave que Gotea",
        "htm_faucet_desc": "Detén el goteo molesto.",
        "htm_caulk_title": "7. Resellar la Tina",
        "htm_caulk_desc": "Previene daños por agua y moho.",
        "htm_showerhead_title": "8. Cambiar Regadera",
        "htm_showerhead_desc": "Mejora tu experiencia de baño.",
        "htm_smell_title": "9. Eliminar Olor a Alcantarilla",
        "htm_smell_desc": "Bloquea los gases llenando las trampas.",
        "htm_washer_hose_title": "10. Cambiar Mangueras",
        "htm_washer_hose_desc": "Previene inundaciones en lavandería."
    },
    'zh': {
        "htm_title": "自己动手做 (DIY)",
        "htm_subtitle": "FAQ 100 中的前 10 大简单房屋维修",
        "htm_joe_title": "Joe AI 助手",
        "htm_joe_desc": "选择一项任务以获取材料计算，或让我导航。",
        "htm_calc_btn": "计算材料",
        "htm_materials": "所需材料",
        "htm_tools": "所需工具",
        "htm_steps": "逐步指南",
        "htm_disposal_title": "1. 解除垃圾处理器卡顿",
        "htm_disposal_desc": "轻松释放卡住的电机。",
        "htm_heater_title": "2. 重置热水器",
        "htm_heater_desc": "热跳闸后恢复热水。",
        "htm_toilet_title": "3. 修复漏水马桶",
        "htm_toilet_desc": "停止持续流水。",
        "htm_sink_title": "4. 清理水槽 P 型管",
        "htm_sink_desc": "物理疏通水槽。",
        "htm_aerator_title": "5. 清洁起泡器",
        "htm_aerator_desc": "解决水槽水压低的问题。",
        "htm_faucet_title": "6. 修复滴水龙头",
        "htm_faucet_desc": "停止烦人的滴水。",
        "htm_caulk_title": "7. 浴缸重新填缝",
        "htm_caulk_desc": "防止水损坏和霉菌。",
        "htm_showerhead_title": "8. 更换淋浴头",
        "htm_showerhead_desc": "升级淋浴体验。",
        "htm_smell_title": "9. 消除下水道异味",
        "htm_smell_desc": "通过注水阻挡气体。",
        "htm_washer_hose_title": "10. 更换洗衣机软管",
        "htm_washer_hose_desc": "防止洗衣房洪水。"
    },
    'tl': {
        "htm_title": "Gawin Mo Mismo (DIY)",
        "htm_subtitle": "Nangungunang 10 Madaling Pag-aayos mula sa FAQ 100",
        "htm_joe_title": "Joe AI Assistant",
        "htm_joe_desc": "Pumili ng gawain para makakuha ng kalkulasyon, o magtanong.",
        "htm_calc_btn": "Kalkulahin ang Materyales",
        "htm_materials": "Mga Kailangang Materyales",
        "htm_tools": "Mga Kailangang Tool",
        "htm_steps": "Step-by-Step",
        "htm_disposal_title": "1. Alisin ang Bara sa Disposal",
        "htm_disposal_desc": "Madaling ayusin ang baradong motor.",
        "htm_heater_title": "2. I-reset ang Water Heater",
        "htm_heater_desc": "Ibalik ang mainit na tubig.",
        "htm_toilet_title": "3. Ayusin ang Running Toilet",
        "htm_toilet_desc": "Itigil ang patuloy na agos ng tubig.",
        "htm_sink_title": "4. Linisin ang Sink P-Trap",
        "htm_sink_desc": "Alisin ang bara sa lababo.",
        "htm_aerator_title": "5. Linisin ang Aerator",
        "htm_aerator_desc": "Ayusin ang mahinang pressure.",
        "htm_faucet_title": "6. Ayusin ang Tumutulong Gripo",
        "htm_faucet_desc": "Itigil ang pagtulo.",
        "htm_caulk_title": "7. I-recaulk ang Bathtub",
        "htm_caulk_desc": "Iwasan ang sira sa tubig at amag.",
        "htm_showerhead_title": "8. Palitan ang Showerhead",
        "htm_showerhead_desc": "I-upgrade ang shower.",
        "htm_smell_title": "9. Tanggalin ang Amoy Imburnal",
        "htm_smell_desc": "Harangan ang gas sa pamamagitan ng tubig.",
        "htm_washer_hose_title": "10. Palitan ang Washer Hoses",
        "htm_washer_hose_desc": "Iwasan ang baha sa laundry."
    },
    'vi': {
        "htm_title": "Tự làm (DIY)",
        "htm_subtitle": "Top 10 Sửa chữa Dễ dàng từ FAQ 100",
        "htm_joe_title": "Trợ lý Joe AI",
        "htm_joe_desc": "Chọn một tác vụ để tính toán vật liệu hoặc yêu cầu điều hướng.",
        "htm_calc_btn": "Tính toán Vật liệu",
        "htm_materials": "Vật liệu cần thiết",
        "htm_tools": "Công cụ cần thiết",
        "htm_steps": "Từng bước một",
        "htm_disposal_title": "1. Tháo kẹt máy xay rác",
        "htm_disposal_desc": "Dễ dàng giải phóng động cơ bị kẹt.",
        "htm_heater_title": "2. Đặt lại Máy nước nóng",
        "htm_heater_desc": "Khôi phục nước nóng sau khi ngắt điện.",
        "htm_toilet_title": "3. Sửa bồn cầu chảy nước",
        "htm_toilet_desc": "Ngừng dòng nước chảy liên tục.",
        "htm_sink_title": "4. Làm sạch P-Trap",
        "htm_sink_desc": "Thông tắc bồn rửa của bạn.",
        "htm_aerator_title": "5. Làm sạch sục khí",
        "htm_aerator_desc": "Khắc phục áp lực nước yếu.",
        "htm_faucet_title": "6. Sửa vòi nước rò rỉ",
        "htm_faucet_desc": "Ngừng nhỏ giọt khó chịu.",
        "htm_caulk_title": "7. Trám lại Bồn tắm",
        "htm_caulk_desc": "Ngăn ngừa hư hỏng và nấm mốc.",
        "htm_showerhead_title": "8. Thay vòi hoa sen",
        "htm_showerhead_desc": "Nâng cấp trải nghiệm tắm.",
        "htm_smell_title": "9. Loại bỏ mùi cống",
        "htm_smell_desc": "Chặn khí bằng cách đổ nước.",
        "htm_washer_hose_title": "10. Thay ống máy giặt",
        "htm_washer_hose_desc": "Ngăn chặn lũ lụt phòng giặt."
    }
}

for lang in ['en', 'es', 'zh', 'tl', 'vi']:
    lang_marker = f'"{lang}": {{'
    if lang_marker in appjs_content:
        injected_str = "\n"
        for k, v in trans[lang].items():
            injected_str += f'        "{k}": "{v}",\n'
        appjs_content = appjs_content.replace(lang_marker, lang_marker + injected_str)

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(appjs_content)
    
print("Added HTM translations to app.js!")
